aws_dbt_snowflake_project:
  outputs:
    dev:
      account: NWZINZY-BS92383
      database: AIRBNB
      password: AdityaBoseSnowflake@21
      role: "ACCOUNTADMIN"
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: BOSEADITYA1994
      warehouse: COMPUTE_WH
  target: dev
